<div class="container py-4">
<?php if ($success !== ''): ?><div class="alert alert-success"><?= $e($success) ?></div><?php endif; ?>
<?php if ($error !== ''): ?><div class="alert alert-danger"><?= $e($error) ?></div><?php endif; ?>
<div class="row g-4">
<div class="col-lg-4">
<div class="card shadow-sm mb-4"><div class="card-body"><h1 class="h4 mb-3">Личный кабинет</h1><p class="mb-2"><strong>Имя:</strong> <?= $e($user['username'] ?: 'Пользователь') ?></p><p class="mb-2"><strong>Email:</strong> <?= $e($user['email']) ?></p><p class="mb-2"><strong>Телефон:</strong> <?= $e($user['phone'] ?: '-') ?></p><p class="mb-2"><strong>Роль:</strong> <?= $e($user['role']) ?></p><p class="mb-0"><strong>Регистрация:</strong> <?= $e(date('d.m.Y H:i', strtotime($user['created_at']))) ?></p></div></div>
<div class="card shadow-sm"><div class="card-body"><h2 class="h5 mb-3">Смена пароля</h2><form method="POST" action="index.php?page=change_password"><input type="hidden" name="csrf_token" value="<?= $e($csrf()) ?>"><div class="mb-3"><label class="form-label">Старый пароль</label><input type="password" name="current_password" class="form-control" required></div><div class="mb-3"><label class="form-label">Новый пароль</label><input type="password" name="new_password" class="form-control" required></div><div class="mb-3"><label class="form-label">Повтор нового пароля</label><input type="password" name="confirm_password" class="form-control" required></div><button type="submit" class="btn btn-dark w-100">Сменить пароль</button></form></div></div>
</div>
<div class="col-lg-8"><div class="card shadow-sm"><div class="card-header bg-white"><h2 class="h5 mb-0">Мои заявки на просмотр</h2></div><div class="card-body">
<?php if ($requests !== []): ?><div class="table-responsive"><table class="table table-hover align-middle"><thead class="table-light"><tr><th>№</th><th>Дата</th><th>Объект</th><th>Цена</th><th>Желаемая дата</th><th>Статус</th><th></th></tr></thead><tbody>
<?php foreach ($requests as $request): ?><tr><td>#<?= (int) $request['request_id'] ?></td><td><?= $e(date('d.m.Y H:i', strtotime($request['created_at']))) ?></td><td><?= $e($request['title']) ?></td><td><?= number_format((float) $request['price'], 0, ',', ' ') ?> ₽</td><td><?= $e($request['preferred_date'] ? date('d.m.Y', strtotime($request['preferred_date'])) : '-') ?></td><td><?php $cls = $request['status'] === 'processed' ? 'success' : 'primary'; ?><span class="badge bg-<?= $cls ?>"><?= $e($request['status']) ?></span></td><td><a href="index.php?page=request_details&id=<?= (int) $request['request_id'] ?>" class="btn btn-sm btn-outline-dark">Подробнее</a></td></tr><?php endforeach; ?>
</tbody></table></div><?php else: ?><p class="text-muted mb-0">У вас пока нет заявок. <a href="index.php?page=catalog">Перейти в каталог</a></p><?php endif; ?>
</div></div></div></div></div>
