<div class="container py-4">
<?php if ($success !== ''): ?><div class="alert alert-success"><?= $e($success) ?></div><?php endif; ?>
<?php if ($error !== ''): ?><div class="alert alert-danger"><?= $e($error) ?></div><?php endif; ?>
<div class="d-flex justify-content-between align-items-center mb-3"><h1 class="h3 mb-0">Панель администратора</h1><div><a href="index.php?page=admin_property_add" class="btn btn-success">+ Добавить объект</a> <a href="index.php?page=admin_requests" class="btn btn-outline-dark">Заявки</a> <a href="index.php?page=admin_seeder" class="btn btn-outline-primary">Seeder</a></div></div>
<div class="card shadow-sm"><div class="card-body">
<?php if ($properties !== []): ?><div class="table-responsive"><table class="table table-bordered align-middle"><thead><tr><th>ID</th><th>Объект</th><th>Район</th><th>Цена</th><th>Статус</th><th>Действия</th></tr></thead><tbody>
<?php foreach ($properties as $property): ?><tr><td><?= (int) $property['id'] ?></td><td><div><strong><?= $e($property['title']) ?></strong></div><div class="small text-muted"><?= $e($property['address']) ?></div></td><td><?= $e($property['district_name']) ?></td><td><?= number_format((float) $property['price'], 0, ',', ' ') ?> ₽</td><td><?= (int) $property['is_published'] === 1 ? '<span class="badge bg-success">Опубликован</span>' : '<span class="badge bg-secondary">Скрыт</span>' ?></td><td><div class="d-flex flex-wrap gap-2"><a href="index.php?page=property&id=<?= (int) $property['id'] ?>" class="btn btn-sm btn-outline-primary">Открыть</a><a href="index.php?page=admin_property_edit&id=<?= (int) $property['id'] ?>" class="btn btn-sm btn-warning">✏️</a><form method="POST" action="index.php?page=admin_toggle_visibility" class="d-inline"><input type="hidden" name="csrf_token" value="<?= $e($csrf()) ?>"><input type="hidden" name="id" value="<?= (int) $property['id'] ?>"><input type="hidden" name="visibility" value="<?= (int) $property['is_published'] === 1 ? 0 : 1 ?>"><button class="btn btn-sm btn-secondary"><?= (int) $property['is_published'] === 1 ? 'Скрыть' : 'Опубликовать' ?></button></form><form method="POST" action="index.php?page=admin_property_delete" class="d-inline" onsubmit="return confirm('Удалить объект?');"><input type="hidden" name="csrf_token" value="<?= $e($csrf()) ?>"><input type="hidden" name="id" value="<?= (int) $property['id'] ?>"><button class="btn btn-sm btn-danger">🗑️</button></form></div></td></tr><?php endforeach; ?>
</tbody></table></div><?php else: ?><p class="text-muted mb-0">Объекты еще не добавлены.</p><?php endif; ?>
</div></div></div>
